---
- name: Make sure nodejs_version is set correctly
  fail: nodejs_version is not set correctly
  when: nodejs_version not in [ "0.10", "0.12" ]

# To install packages that need to be built from source
- name: Make sure build-essential is installed
  apt:
    name: build-essential
    state: present

- name: Add NodeSources apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSources repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"

- name: Ensure nodeJS and npm are installed
  apt:
    name: "nodejs={{ nodejs_version }}.*"
    state: present
    update_cache: yes

- name: Install forever (to run nodeJS apps)
  npm: 
    name: forever
    global: yes
    state: latest
  when: nodejs_forever

- name: Install additional defined npm global packages
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  with_items: nodejs_npm_global_packages
